---

- name: Create self-signed certificate
  ansible.builtin.command: "{{ item }}"  # noqa no-changed-when
  args:
    chdir: "{{ ail_root }}/bin/helper/gen_cert"
  with_items:
    - bash gen_root.sh
    - bash gen_cert.sh

- name: Check resulting cert files
  ansible.builtin.command: "ls -lA {{ ail_root }}/bin/helper/gen_cert"
  changed_when: false

- name: Copy cert files
  ansible.builtin.copy:
    src: "{{ ail_root }}/bin/helper/gen_cert/{{ item }}"
    dest: "{{ ail_root }}/var/www/{{ item }}"
    owner: "{{ ail_user }}"
    mode: '0400'
    remote_src: true
  with_items:
    - server.crt
    - server.key
  become: yes
