---

- block:
    - name: nginx AIL configuration
      ansible.builtin.template:
        src: "{{ ail_nginx_template }}"
        dest: "{{ apache_sitedir }}/ail"
        owner: '0'
        group: '0'
        mode: '0644'
      notify:
        - restart nginx
    - name: enable AIL nginx site
      ansible.builtin.file:
        src: "{{ apache_sitedir }}/ail"
        dest: "/etc/nginx/sites-enabled/ail"
        state: link
        mode: '0644'
      notify:
        - restart nginx
  when: ansible_os_family == 'Debian'
