FROM alpine:3.4
RUN apk update

# Install Ansible
RUN apk add git ansible python python-dev py-pip
RUN pip install ansible-lint
RUN mkdir /etc/ansible

# Install Ansible inventory file
RUN (echo "[local]"; echo "localhost ansible_connection=local") > /etc/ansible/hosts
RUN (echo "[defaults]"; echo "callback_whitelist = profile_tasks, timer") > /etc/ansible/ansible.cfg
