---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    - faup_virtualenv_path: "{{ ail_virtualenv }}"
    - faup_virtualenv_user: "{{ ail_user }}"
    - faup_virtualenv_home: "{{ ail_home }}"
    - faup_ownership:
        - { d: "{{ ail_home }}/.cache/pip", s: directory, m: '0755', o: "www-data" }
        - { d: "{{ toolsetdir }}/faup/src/lib/bindings/python/build", s: directory, m: '0755', o: "{{ ail_user }}" }
        - { d: "{{ toolsetdir }}/faup/src/lib/bindings/python/pyfaup.egg-info", s: directory, m: '0755', o: "{{ ail_user }}" }
    - tlsh_virtualenv_path: "{{ ail_virtualenv }}"
    - tlsh_virtualenv_user: "{{ ail_user }}"
    - tlsh_virtualenv_home: "{{ ail_home }}"
    - tlsh_version: a67c69b0cdfd168c62c159d41b8a3612ee2b0df1
    - redis_configure: false
  pre_tasks:
    - name: Ubuntu | Install python3
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: RedHat | Install python3
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Gather Facts
      setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
  roles:
    - juju4.ail_framework
